services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn models4pt.app:app --host 0.0.0.0 --port 8000 --reload
