name: Generate Changelog

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug git log
        run: |
          git log --pretty=format:"* %h - %s (%an, %ad)" --date=short || echo "git log failed"

      - name: Generate Changelog
        run: |
          git log --pretty=format:"* %h - %s (%an, %ad)" --date=short > CHANGES.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGES.md
          git commit -m "Update changelog"
          git push