name: Generate Changelog
on:
  push:
    branches:
      - master
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full commit history
      - name: Generate Full Changelog
        run: |
          git log --pretty=format:"* %h - %s (%an, %ad)" --date=short > CHANGES.md
      - name: Debug CHANGES.md
        run: cat CHANGES.md || echo "CHANGES.md not created."
      - name: Commit and Push Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGES.md
          git commit -m "Update changelog"
          git push

